# This is a basic workflow to help you get started with Actions

name: download economists mobi

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: master
    paths:  
      - 'Changelog'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Initialize Environment
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

#    - name: Debugging with tmate
#      uses: mxschmitt/action-tmate@v2

    # Runs a single command using the runners shell
    - name: Download the Economists mobi
      run: |
        mkdir mobi/ && cd mobi/
        ebook-convert "The Economist.recipe" `date +%Y%m%d`.mobi
      

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
         # Artifact name
        name: Latest mobi
    # Directory containing files to upload
        path: ./mobi/

