# This is a basic workflow to help you get started with Actions

name: download economists 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
#on:
#  push:
#    branches: master
#    paths:  
#      - 'Changelog'
on: 
  schedule:
    - cron: "0 10 * * 5"
  workflow_dispatch:
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Required Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libegl1 \
          libopengl0 \
          libxcb-cursor0
    
    - name: Initialize Environment
      env:
          DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

#    - name: Debugging with tmate
#      uses: mxschmitt/action-tmate@v2

    # Runs a single command using the runners shell

    - name: Download the Economists 
        # mkdir mobi/ && cd mobi/
        # ebook-convert "The Economist.recipe" `date +%Y%m%d`.mobi
      run: |
        mkdir eco/ && cd eco/
        ebook-convert "The Economist.recipe" `date +%Y%m%d`.mobi        

    - name: Set Date
      id: vars
      run: echo "date=$(date +%Y%m%d)" >> $GITHUB_ENV
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
         # Artifact name
        name: "eco-${{ env.date }}"
    # Directory containing files to upload
        path: ./
        
